name: Deploy 360 backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t imgeval360 -f ./eval360/Dockerfile .
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "back360"  # Reemplaza "store-demo-api2" con el nombre de tu aplicación Heroku
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
