name: Deploy Frontend 360

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3.7.0
      with:
        node-version: '18.18.0'

    - name: Install dependencies
      working-directory: ./eval360_Angular
      run: npm install

    - name: Build
      working-directory: ./eval360_Angular
      run: npm run build --prod

    - name: Index for routing
      run: mv ./eval360_Angular/dist/Evaluacion360/index.html ./eval360_Angular/dist/Evaluacion360/404.html

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.1.0
      with:
        publish-dir: ./eval360_Angular/dist/Evaluacion360
        production-deploy: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
